### PR TITLE
Adds uniqueness in the default AP name

### PR DESCRIPTION
**Pull request by ClemRz**
Hi,

I'd like to propose a small enhancement to your awesome library.
When I had students working on ESP8266 using the Basic firmware they had trouble identifying which AP correspond to which hardware, this because they were all named "ESP" by default.

The enhancement I suggest is using either the MAC address or any unique identifier (MAC address sounds sound) to build the default AP name.

Thanks.

### CODE REVIEW

**Comment by ClemRz** [comment]
Thanks! Deleting the branch.

**Comment by mmiscool** [comment]
I noticed you said you were using these with student in a class. Have you developed activities or coriculum that might be shared. I would really like to make esp basic freindly enough to be used in schools.

**Comment by ClemRz** [comment]
Hi,
Yes, I developped several IoT projects that can be performed in a classroom.
I wrote the one using ESP8266 with the ESP Basic firmware on Instructables.com:
[www.instructables.com/id/4-WiFi-Door-Alarm-Using-a-ESP8266-IoT/](www.instructables.com/id/4-WiFi-Door-Alarm-Using-a-ESP8266-IoT/)
I think that ESP Basic is already very friendly! I love it!

**Comment by ClemRz** [comment]
Hi @mmiscool, do you think I could have a 512k bin build of the version with wifi uniqueness please?
I will need it for a workshop with 10 students on Thursday.
Thanks!

**Comment by mmiscool** [comment]
I think i can produce a build. Is it your intent to use the 2.0 branch or would you rather the 3.0 branch. I might be able to strip the tft stuff out of the 3.0 build?

**Comment by ClemRz** [comment]
I think 2.0 is ok, I just don't have the toolchain right now to compile with that change (uniqueness of SSID).

**Comment by mmiscool** [comment]
This is the bin file for the latest 2.0 branch 512 k. Check it to make sure it will work for you and send me a msg if you have any problems. 
[ESP8266Basic.cpp.zip](https://github.com/esp8266/Basic/files/443633/ESP8266Basic.cpp.zip)

**Comment by ClemRz** [comment]
It works great! Thanks a lot!

**Pull request merged**
